### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by poloka** [es-shims/array-includes#22]
Would like to know when the next release of array-includes will occur?  Awaiting a fix currently on master.

**Comment by ljharb** [comment]
I suppose I could release it any time; but the only unreleased fix on master is dbf88e0c15f23f10bd4abe6a666910e0a3cc53b6 which has a comment "there are no implementations where this is the case" - do you have an implementation where this is a problem?

**Comment by poloka** [comment]
I'm running into this issue with running IE11 in IE10 compatibility mode.

**Comment by ljharb** [comment]
ew, IE compatibility mode :-/

thanks, will release shortly.

**Comment by ljharb** [comment]
v3.0.3 published.
