### ISSUE TITLE
Does not work with string in boxedstring bug environments

### ISSUE THREAD

**Issue by Xotic750** [es-shims/array-includes#29]
For example Opera 10.10
`Array.prototype.includes.call('abc', 'c'); // => false but should be true`
Low priority stuff. :)

**Comment by ljharb** [comment]
This test passes in Opera 10.6 and 11.1.

**Comment by ljharb** [comment]
The tests fail in IE 8, however.

**Comment by ljharb** [comment]
I've fixed things for IE 8; can't reproduce in Opera 10.6 or 11.
