### ISSUE TITLE
URGENT: es-abstract module breakup has broken latest version on fusebox bundler

### ISSUE THREAD

**Issue by jpike88** [es-shims/array-includes#45]
https://github.com/es-shims/array-includes/commit/c7fd1a05e94bcb36c0c7ffa3e8651a68dd88f700

This commit has caused my bundler to freak out. Are you sure you're referencing es-abstract correctly? Their documentation states:

```All abstract operations will also be available under an es5/es2015/es2016/es2017/es2018/es2019 entry point, and exported property, if you require a specific version.```

Yet your code is using syntax like

```var ToInteger = require('es-abstract/2018/ToInteger');```

You're referencing a folder path that's not actually being exposed by the es-abstract module.

```var ToInteger = require('es-abstract/es2018/ToInteger');``` if I'm not mistaken.

if so please push a new version out asap, this will likely be breaking across a whole range of bundlers.

**Comment by ljharb** [comment]
It’s definitely exposed by v1.17.0-next.0 and v1.17.0-next.1, both of which are valid in the semver range in the linked commit. Tests pass in many packages using these versions.

Are you doing any kind of dependency resolution override? Does `npm ls` exit successfully?

**Comment by ljharb** [comment]
I have forgotten to update es-abstract’s readme; thanks for the reminder to do that.

**Comment by jpike88** [comment]
I’m looking at the latest version on master. The entry point is index.js. 

https://github.com/ljharb/es-abstract/blob/master/index.js

It doesn’t expose a property called 2018, and the fuse box bundler is breaking as a result. While the true folder path may exist, the index.js is used as the sole source of truth here

**Comment by ljharb** [comment]
It's not supposed to. `es-abstract/2018/ToInteger` is a *file path*, not a property.

**Comment by ljharb** [comment]
CJS modules are just a file system. node resolution looks up the "main" when requiring a directory, but every file on the filesystem is directly accessible.

I'm not familiar with "fusebox bundler", can you elaborate on what it is? (The primary bundlers used in the JS ecosystem are webpack and browserify, and others include rollup, parcel, pika, metro; i've never heard of any others)

**Comment by jpike88** [comment]
Fusebox is a bundler like webpack etc, but it’s designed for minimal config and maximum performance

@nchanged i might be a little out of my depth here could you weight in

**Comment by ljharb** [comment]
Specifically, `es-abstract/2018/ToInteger` maps - by node's module resolution algorithm which in this respect has been unchanged for a decade - to this file: https://unpkg.com/browse/es-abstract@1.17.0-next.1/2018/ToInteger.js

**Comment by ljharb** [comment]
@jpike88 I see https://github.com/fuse-box/fuse-box/pull/1642 has been merged into master for fusebox but not released; the implication is that https://github.com/fuse-box/fuse-box/issues/1641 might be the problem.

**Comment by jpike88** [comment]
I’m sitting on next.155 version so I’d be maybe only a couple of weeks out of date with master

**Comment by ljharb** [comment]
In that case, I'm not sure - but I'm convinced it's either a configuration issue on your end, or a bug in fusebox, since deep requires are a quite reliable pattern.

**Comment by nchanged** [comment]
sorry guys, the latest commit broke the resolver, and unfortunately, that wasn't covered with tests.

**Comment by ljharb** [comment]
@nchanged thanks, so to confirm, this was just a bug in fusebox?

**Comment by nchanged** [comment]
@ljharb yeah, the latest commit pushed the parent node_modules to the array which is essentially wrong, resulted in picking up a different version of `es-abstract` located there. All good now! ;-)
