### ISSUE TITLE
Extraneous test.html file in v3.1.1 NPM package

### ISSUE THREAD

**Issue by gorner** [es-shims/array-includes#50]
As part of a review of updated dependencies associated with a package upgrade in our app, I noticed the NPM package of array-includes v3.1.1 introduces a large "test.html" file which is not part of the GitHub repo: https://diff.intrinsic.com/array-includes/3.1.0/3.1.1#file-test.html

I have no reason to believe it's harmful, but I doubt this is needed by dependent packages and it looks like this is contributing to an unpacked size of [822 kB](https://www.npmjs.com/package/array-includes/v/3.1.1) for the package (vs. [23.4 kB for v3.1.0](https://www.npmjs.com/package/array-includes/v/3.1.0)).

**Comment by ljharb** [comment]
Indeed, it’s the output of `testling --html`. I’ll make sure the next version doesn’t include it, but disk space isn’t really a big deal and it’s not part of the bundle, so i don’t think it’s worth issuing a new patch.

**Comment by nikolay-borzov** [comment]
The package has more extra files `.github`, `test`, `.travis.yml`.
Agree, space isn’t really a big deal, but download time matters.

**Comment by ljharb** [comment]
Everything's gzipped - tests aren't extra files, they're very intentionally included in every package I maintain, and `.github` and `.travis.yml` are so tiny that excluding them won't improve download size.
